cmcc:
  ingressbuilder: blueprint
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
spring:
  devtools:
    add-properties: false
  application:
    name: cmcc-operator
  main:
    banner-mode: off
---
logging:
  level:
    com:
      tsystemsmms: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    probes:
      enabled: true
spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  main:
    banner-mode: console
