apiVersion: v1
kind: Namespace
metadata:
  name: cmcc-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cmcc-operator
  namespace: cmcc-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmcc-operator
  namespace: cmcc-operator
spec:
  selector:
    matchLabels:
      app: cmcc-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: cmcc-operator
    spec:
      serviceAccountName: cmcc-operator
      containers:
        - name: operator
          image: ghcr.io/t-systems-mms/cmcc-operator/cmcc-operator:latest
          imagePullPolicy: Always
          env:
            - name: CMCC_INGRESSBUILDER
              value: "blueprint"
            - name: CMCC_USECONFIGMAP
              value: "false"
            - name: CMCC_USECRD
              value: "true"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-admin
subjects:
  - kind: ServiceAccount
    name: cmcc-operator
    namespace: cmcc-operator
roleRef:
  kind: ClusterRole
  name: cmcc-operator
  apiGroup: ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cmcc-operator
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
      - "extensions"
    resources:
      - deployments
      - configmaps
      - jobs
      - pods
      - persistentvolumeclaims
      - secrets
      - services
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - '*'
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - '*'
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - "cmcc.tsystemsmms.com"
    resources:
      - coremediacontentclouds
      - coremediacontentclouds/status
    verbs:
      - '*'
