{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cmcc-operator.fullname" . }}
  labels:
    {{- include "cmcc-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cmcc-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "cmcc-operator.fullname" . }}
  apiGroup: ""
{{- end }}