name: build-push
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
          cache: gradle
      - id: repository
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}/cmcc-operator
      - name: push
        uses: gradle/gradle-build-action@v2
        with:
          arguments: >
            build jib 
            -Djib.to.image=ghcr.io/${{ steps.repository.outputs.lowercase }}:${{github.ref_name}}
            -Djib.to.tags=${{github.ref_name}},latest
            -Djib.to.auth.username=${{ github.actor }}
            -Djib.to.auth.password=${{ github.token }}

